build.version: @project.version@
moduleName: @moduleName@

server:
  port: ${PORT:10000}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @project.name@
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        query:
#          fail_on_pagination_over_collection_fetch: true
#        types:
#          print:
#            banner: false
#    open-in-view: false
#  liquibase:
#    change-log: classpath:liquibase/db.changelog-master.xml
  sleuth:
    sampler:
      probability: 1.0

  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true

management:
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
      path-mapping:
        health: actuator/health
        info: actuator/info
        prometheus: metrics

logbook:
  exclude:
    - /actuator/health
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /v3/api-docs.yml
    - /swagger-ui.html
    - /admin/**
    - /webjars/**
    - /swagger-resources/**
    - /swagger-ui/**
    - /metrics
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  format:
    style: json
  strategy: body-only-if-status-at-least
  minimum-status: ${MINIMUM_STATUS_LOG_BODY:400}

logging:
  level:
    ROOT: INFO
#    org.zalando.logbook.Logbook: TRACE
    org.zalando.logbook.Logbook: OFF
  pattern:
    console: "${moduleName}_${spring.application.name} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([-,%X{traceId:-},%X{spanId:-}]){blue}[%thread] %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"

clients:
  settings:
    dozory:
      connection-timeout: 100s
      read-timeout: 100s
      connection-manager:
        default-max-per-route: 100
        max-total: 100

telegram-bot:
  properties:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}